/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  umouse forte                             */
/*      FILE         :  main.cpp                         */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX700                                  */
/*      CPU TYPE     :  RX71M                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/

/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 08/07/2013                                        */
/************************************************************************/

#include "iodefine.h"

#ifdef CPPAPP
//Initialize global constructors
extern "C" void __main() {
    static int initialized;
    if (!initialized) {
        typedef void (*pfunc)();
        extern pfunc __ctors[];
        extern pfunc __ctors_end[];
        pfunc *p;

        initialized = 1;
        for (p = __ctors_end; p > __ctors;)
            (*--p)();
    }
}

#endif 

#include <stdint.h>

#include <array>
#include "clock.h"
#include <uart.h>
#include "gpio.h"
#include <timeInterrupt.h>
#include "spi.h"
#include "timer.h"
#include "ad.h"
#include "pwm.h"
#include "phaseCounting.h"
#include "dataFlash.h"

#include <imu.hpp>
#include "da.h"
#include <myUtil.hpp>
#include "sound.h"
#include "tactsw.h"
#include "fcled.h"
#include "mode.h"

#include "maze.h"
#include "mouse.h"
#include "wallsensor.hpp"
#include "gamepad.h"

#include "moveEvent.h"
#include "communication.h"

#include "parameterManager.h"


//namespaceの宣言
using namespace robot_object;
namespace peri = peripheral_RX71M;
using peri::getElapsedMsec;
using peri:: waitmsec;

//プロトタイプ宣言
void periperalInit();
void startUpInit();
void lowBatteryAlert();

//-------------タイマ割り込み関数---------------//
extern "C" void timeInterrupt(void);

//250usec毎に呼ばれる
void timeInterrupt(void) {
    //http://japan.renesasrulz.com/cafe_rene/f/69/t/1515.aspx 多重割り込み　資料
    __builtin_rx_setpsw('I');

    static uint64_t countIntNum = 0;

    //--------------------------------------//
    MPU9250 &imu1 = MPU9250::getInstance();
    Icm20608G &imu2 = Icm20608G::getInstance();
    TactSw &tsw = TactSw::getInstance();
    FcLed &fcled = FcLed::getInstance();
    WallSensor &wallSen = WallSensor::getInstance();
    Gamepad &gamepad = Gamepad::getInstance();
    EventList &events = EventList::getInstance();
    UMouse &mouse = UMouse::getInstance();

    //UARTの送受信処理
    if (countIntNum % 7 == 0) {
        peri::sendDataSCIFA9();

    }
    peri::recieveDataSCIFA9();
    fetchCommand();

    //30msec毎の処理
    if (countIntNum % 120 == 0) {
        sendPeriodicMsg();
    }
    //1msec毎の処理
    if(countIntNum % 4 == 0){
        if(getElapsedMsec()>5000){
            imu1.update();
            imu2.update();
        }
    }
    if (countIntNum % 4 == 1){

        tsw.update();
        fcled.update();
        gamepad.update();
        events.update();
    }
    if (countIntNum % 4 == 2){
        mouse.update();
    }


    float vol_f = 15.1 / 5.1 * (S12AD.ADDR0) * 3.3 / 4096;
    if (countIntNum % 1000 == 0){
        if(vol_f < 6.8)famima();
    }

    //リセットコマンドの監視
    if(gamepad.BACK >0 &&
       gamepad.LB >0 &&
       gamepad.LT >0 ){
       SYSTEM.PRCR.WORD = 0xA502;
       SYSTEM.SWRR = 0xA501;
    }

    //ブートモードへの変更
    if(gamepad.RB > 0 &&
       gamepad.RT > 0 &&
       gamepad.START > 0){
        PORTD.PODR.BIT.B7 = 0; //PICの入力ピンをローにする
    }

    //壁センサの更新処理
/*    switch(countIntNum % 4){
        case 0:
            wallSen.updateAllOffVal();
            //wallSen.turnOnLeftLed();
            wallSen.turnOnAllLed();
            break;
        case 1:
            //wallSen.updateLeftOnVal();
            wallSen.updateAllOnVal();
        	wallSen.turnOffAllLed();
            //wallSen.turnOnRightLed();
            break;
        case 2:
            //wallSen.updateRightOnVal();
            //wallSen.turnOffAllLed();
            //wallSen.turnOnAheadLed();
            wallSen.turnOffAllLed();
        	break;
        case 3:
            //wallSen.updateAheadOnVal();
            wallSen.turnOffAllLed();
            wallSen.modulateVal();
            break;
    }
*/
    //毎回行う処理

    wallSen.updateAllOffVal();
    wallSen.turnOnAllLed();

    //時間稼ぎ
    soundUpdate();
    peri::startAD_AN000(); //電源
    //時間稼ぎ終わり
    wallSen.updateAllOnVal();
    wallSen.turnOffAllLed();
    wallSen.modulateVal();

    //wallSen.turnOffAllLed();
    //wallSen.updateAllOffVal();
    //wallSen.turnOnLeftLed();
    //wallSen.turnOnAllLed();


    //peri::startAD_AN002(); //左センサ
    //peri::startAD_AN003(); //右センサ
    //peri::startAD_AN001(); //左前センサ
    //peri::startAD_AN004(); //右前センサ


    countIntNum++;
    peri::endTimeuCountIntCMT0();

}

//-------------メイン関数---------------//
int main() {
    periperalInit();
    startUpInit();

    MPU9250& imu1 = MPU9250::getInstance();
    Icm20608G& imu2 = Icm20608G::getInstance();
    FcLed& fcled = FcLed::getInstance();
    UMouse  &mouse = UMouse::getInstance();

    //addBgmList(otenba);

    while(1){
        printfAsync("entry point \n");
        ///////////////////////////////////////
        MPU9250::getInstance().calibOmegaOffset(200);
        MPU9250::getInstance().calibAccOffset(200);
        float a = 1.0;
        float b = 2.0;
        float c = 3.0;
        float d = -1.0;
        float e = -2.0;
        float f = -3.0;
        ParameterManager &pm = ParameterManager::getInstance();
/*
        pm.write(0,a);
        pm.write(1,b);
        pm.write(2,c);
        pm.write(3,d);
        pm.write(4,e);
        pm.write(5,f);
*/
        printfAsync("%f, %f, %f \n",pm.read(0),
                                   pm.read(1),
                                   pm.read(2)
                                 );

        printfAsync("%f, %f, %f \n",pm.read(3),
                                   pm.read(4),
                                   pm.read(5)
                                 );
        printfAsync("%f, %f, %f \n",pm.read(0),
                                   pm.read(1),
                                   pm.read(2)
                                 );

        printfAsync("%f, %f, %f \n",pm.read(3),
                                   pm.read(4),
                                   pm.read(5)
                                 );



        modeSelect();
    };

    return 0;
}

//各ペリフェラルの初期化
void periperalInit() {
    //クロック
    peri::initClock();
    //IOピン
    peri::initGPIO();
    //UART
    peri::initSCI1();
    peri::initSCIFA9();

    //割り込み関数
    peri::initCMT0();
    peri::initCMT1();

    //SPI
    peri::initRSPI0();
    peri::initRSPI1();

    //時間測定
    peri::initTPU0();
    peri::initCMTW0();
    peri::initCMTW1();

    //AD
    peri::initAD();

    //位相係数
    peri::initMTU1();
    peri::initMTU2();

    //PWM
    peri::initMTU3();
    peri::initMTU4();

    //DA
    peri::initDA();
    printfAsync("-------各種ペリフェラル初期化完了-------\n");

    //データフラッシュ
    peri::initDataFlash();
};

//起動時の処理
void startUpInit() {

    peri::setDutyMTU3(0.0);
    peri::setDutyMTU4(0.0);

    peri::setPriorityCMT0(12);
    peri::setPriorityCMT1(15);
    peri::startCMT0();
    printfAsync("-------CMT0割り込み開始-------\n");

    MPU9250& imu1 = MPU9250::getInstance();
    Icm20608G& imu2 = Icm20608G::getInstance();

    imu1.init();
    imu2.init();

    //sound

    peri::startCMT1();
    printfAsync("-------CMT1割り込み開始-------\n");

    /////////////コンパイル時固有文字列/////////
    printfAsync("Compile Date\n %s\n", __DATE__);
    uint16_t compile_hash = 0;
    for (int i = 0; i < sizeof(__TIME__); i++) {
        compile_hash += __TIME__[i];
    }

    printfAsync("Compile HASH: %d\n", compile_hash);
    printfAsync("Compile TIME: %s\n", __TIME__);
    printfAsync("Compile FILE: %s\n", __FILE__);
    printfAsync("---------------------------\n");
    GB();
    waitmsec(1800);
    randomNote(compile_hash);
    waitmsec(400);
    /////////////電池電圧警告////////////////
    uint16_t vol_ad_val = peri::getAD_AN000();
    float vol_f = 15.1 / 5.1 * (vol_ad_val) * 3.3 / 4096;
    uint8_t num_1V = uint8_t(vol_f);
    uint8_t num_0_1V = uint8_t((vol_f - float(num_1V)) * 10.0);
    for (int i = 0; i < num_1V; i++) {
        SEA();
        if (i == 4)
            waitmsec(250);
        else
            waitmsec(125);
    }
    waitmsec(125);
    for (int i = 0; i < num_0_1V; i++) {
        SEB();
        if (i == 4)
            waitmsec(250);
        else
            waitmsec(125);
    }
    waitmsec(125);

    printfAsync("===finish init====\n");

};


void lowBatteryAlert(){
    uint16_t vol_ad_val = peri::getAD_AN000();
    float vol_f = 15.1 / 5.1 * (vol_ad_val) * 3.3 / 4096;
    if(vol_f < 7.0)famima();
};

